add header to use secondary db in file api status and last modified calls (WP-672)
Smartling/api-sdk-php pull request #131
Opened 2021-11-30 10:49 UTC by vsolovei-smartling

2021-11-30 10:49 UTC, vsolovei-smartling commented on src/File/FileApi.php
> -     *
Parent phpdoc empty, nothing to inherit

2021-11-30 10:50 UTC, vsolovei-smartling commented on src/File/FileApi.php
>      }
Methods were identical

2021-11-30 13:30 UTC, dimitrystd requested changes
Let's discuss other options. I'm not sure we would like to share this header in public sdk.

2021-11-30 13:42 UTC, vsolovei-smartling commented
> Let's discuss other options. I'm not sure we would like to share this header in public sdk.

WordPress calls these api methods, so we're limited with possible solutions. I think the best way then would be to allow injecting custom http client to FileApi. Other alternatives I see are:

- make a private fork of the repo (somewhat increase the amount of maintenance when adding other WordPress related changes, but not by much, hopefully)
- copy api to WordPress repository (much greater initial effort)

2021-12-02 12:46 UTC, PavelLoparev commented
Should we close this since it was resolved in another way?

2021-12-02 14:53 UTC, vsolovei-smartling commented
Resolved in another way

2021-12-02 14:53 UTC, closed without merging