add batch api v2
Smartling/api-sdk-php pull request #143
Opened 2024-04-03 11:50 UTC by vsolovei-smartling

2024-04-03 12:37 UTC, dimitrystd approved these changes

2024-04-03 12:56 UTC, PavelLoparev requested changes
You can ignore comments about `ArrayShape` etc phpdoc "helpers" but in general it makes no sense at all. It probably even only works in some exact version of phpstorm, idk

2024-04-03 12:56 UTC, PavelLoparev commented on src/Batch/BatchApiV2.php
> +    private const GET_BATCH_STATUS_ARRAY_SHAPE = [
This is nonsense. Typehinting through the php doc.. It makes no sense for type safety at all. Moreover, works only in php storm. why should I read these lines in another ide?

2024-04-03 12:56 UTC, PavelLoparev commented on src/Batch/BatchApiV2.php
> +        #[ExpectedValues(['CANCEL_FILE', 'REGISTER_FILE'])]
The same. It's only for autocompletion, it's ridiculous. You can put whatever you want in `$action` - nothing happens.

2024-04-03 12:56 UTC, PavelLoparev commented on src/Batch/BatchApiV2.php
> +        array $localeWorkflows = []
Why don't we introduce params dto?

2024-04-03 12:56 UTC, PavelLoparev commented on src/Batch/BatchApiV2.php
> +        string $callbackUrl = null
Same here - looks weird we don't pass params object here as usual

2024-04-03 12:58 UTC, PavelLoparev commented on src/Batch/BatchApiV2.php
> +    private const GET_BATCH_STATUS_ARRAY_SHAPE = [
I mean, our code "knows" about the ide it's being edited in, this is weird. idk, maybe I don't get the whole idea

2024-04-08 11:26 UTC, vsolovei-smartling commented
I've removed unnecessary code

2024-04-08 17:19 UTC, dimitrystd approved these changes

2024-04-09 07:28 UTC, PavelLoparev approved these changes

2024-04-15 11:19 UTC, merged